##
# This is configuration for the archiving-portion of the workflow. 
# There are 4-5 steps to archiving:
#     0. PRE-PURGE - (only applies to certain outputs) - Remove extraneous files that we do not
#                    want to archive.
#     1. COMPRESSION of the directories. **NOTE** In some cases, unnecessary files will be removed, 
#          see the archive.zsh script
#     2. TRANSFERRING of the directories to another host
#     3. ARCHIVING the directories to mass storage
#     4. PURGING the directories.
# In this file, we specify whether or not to perform each of these steps for each of 
# the output directories.
# Note that since compression and transferring occur before 
##

# If this is FaLsE, do not do any archiving
export PERFORM_ARCHIVE='TRUE'

# Top level directory in HSMS to store experiments
export MSS_TOP_DIR='/HFIP/hur-aoml/5year/Javier.Delgado/osse/experiments/'
# Host where corresponding directories will be transferred when TRANSFER_* is TRUE
export DESTINATION_HOST='storm'
# Top-level directory in $DESTINATION_HOST where directories will be transferred
export DESTINATION_TOPDIR='/home/Javier.Delgado/www/experiments'
 
# Setting the following variables to 'TRUE' will result in the respective
# run directories being compressed. In some cases, this also means that 
# certain files will be deleted. e.g. For Diapost, only the *.txt files will
# be archived. See the archive.zsh script.
export COMPRESS_EXEC_DIRECTORY='TRUE'
export COMPRESS_WPS_DIRECTORIES='FALSE'
export COMPRESS_ATMOS_DIRECTORIES='FALSE'
export COMPRESS_GSI_GES_DIRECTORIES='TRUE'
export COMPRESS_GSI_ANALYSIS_DIRECTORIES='TRUE'
export COMPRESS_ENKF_DIRECTORIES='TRUE'
export COMPRESS_POSTPROC_DIRECTORIES='TRUE'
export COMPRESS_PRODUCTS_DIRECTORIES='TRUE'

# Setting the following variables to 'TRUE' will result in the respective
# run directories being transferred to $DESTINATION_HOST at 
# $DESTINATION_TOPDIR/<whatever destination path scheme is used in archive.zsh>
export TRANSFER_EXEC_DIRECTORY='FALSE'
export TRANSFER_WPS_DIRECTORIES='FALSE'
export TRANSFER_ATMOS_DIRECTORIES='FALSE'
export TRANSFER_GSI_GES_DIRECTORIES='FALSE'
export TRANSFER_GSI_ANALYSIS_DIRECTORIES='FALSE'
export TRANSFER_ENKF_DIRECTORIES='FALSE'
export TRANSFER_POSTPROC_DIRECTORIES='FALSE'
export TRANSFER_PRODUCTS_DIRECTORIES='FALSE'

# Setting the following variables to 'TRUE' will result in the respective
# directories being sent to HSMS. 
## **NOTES**: 
#      1. The archive.zsh script will decide whether to transfer compressed or full directories.
#      2. Except for POSTPROC, all of these must have the corresponding "COMPRESS" 
#         setting above set to 'TRUE' in order to be archived.
export ARCHIVE_EXEC_DIRECTORY='TRUE'
export ARCHIVE_WPS_DIRECTORIES='FALSE'
export ARCHIVE_ATMOS_DIRECTORIES='FALSE'
export ARCHIVE_GSI_GES_DIRECTORIES='TRUE'
export ARCHIVE_GSI_ANALYSIS_DIRECTORIES='TRUE'
export ARCHIVE_ENKF_DIRECTORIES='TRUE'
export ARCHIVE_POSTPROC_DIRECTORIES='TRUE'
export ARCHIVE_PRODUCTS_DIRECTORIES='TRUE'


# Setting the following variables to 'TRUE' will result in the respective
# run directories being purged after being successfully archived and transferred
# export PURGE_EXEC_DIRECTORY='FALSE' # impossible for now
export PURGE_WPS_DIRECTORIES='TRUE'
export PURGE_ATMOS_DIRECTORIES='TRUE'
export PURGE_GSI_GES_DIRECTORIES='FALSE'
export PURGE_GSI_ANALYSIS_DIRECTORIES='FALSE'
export PURGE_ENKF_DIRECTORIES='FALSE'
export PURGE_POSTPROC_DIRECTORIES='FALSE'
export PURGE_PRODUCTS_DIRECTORIES='FALSE'

#
# Settings for specific files
#
# remove the wrf_inout files generated by GSI?
export PURGE_GSI_ANALYSIS_FILES='TRUE'
# remove the analysis.ensmean files generated by the EnKF?
export PURGE_ENKF_ANALYSIS_MEAN_FILES='FALSE'
# remove the firstguess.ensmean files generated by the EnKF?
export PURGE_ENKF_FIRSTGUESS_MEAN_FILES='FALSE'
# Remove the individual members' analysis files (analysis.memNNN)
export PURGE_ENKF_ANALYSIS_ENSEMBLE_FILES='TRUE'
# Remove the individual members' firsguess files (firstgues.memNNN)
export PURGE_ENKF_FIRSTGUESS_ENSEMBLE_FILES='TRUE'
# Retains the Diapost fcst_track files on the file system
export RETAIN_DIAPOST_FCST_TRACK_FILES='TRUE'
